// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pictures.DAL;

#nullable disable

namespace Pictures.DAL.Migrations
{
    [DbContext(typeof(PicturesDbContext))]
    partial class PicturesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pictures.Domain.Entities.Picture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Picture");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "/img/lotos.jpg",
                            Name = "Lotos",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "/img/night city.jpg",
                            Name = "Night city",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Address = "/img/puppy.jpg",
                            Name = "Puppy",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Address = "/img/snowflake.jpg",
                            Name = "Snowflake",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            Address = "/img/misty forest.jpg",
                            Name = "Misty forest",
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            Address = "/img/rabbit.jpg",
                            Name = "Rabbit",
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            Address = "/img/tulip.jpg",
                            Name = "Tulip",
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            Address = "/img/zurich.jpg",
                            Name = "Zurich",
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            Address = "/img/evening sea.jpg",
                            Name = "Evening sea",
                            UserId = 2
                        },
                        new
                        {
                            Id = 10,
                            Address = "/img/bear.jpg",
                            Name = "Bear",
                            UserId = 2
                        },
                        new
                        {
                            Id = 11,
                            Address = "/img/cat.jpg",
                            Name = "Cat",
                            UserId = 2
                        },
                        new
                        {
                            Id = 12,
                            Address = "/img/helix nebula.jpg",
                            Name = "Helix nebula",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Pictures.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Alex@mail.com",
                            Login = "Alex123",
                            Name = "Alex",
                            Password = "12345",
                            Role = 0,
                            Surname = "Xela"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Daniel@mail.com",
                            Login = "Daniel321",
                            Name = "Daniel",
                            Password = "54321",
                            Role = 0,
                            Surname = "Lainad"
                        });
                });

            modelBuilder.Entity("Pictures.Domain.Entities.Picture", b =>
                {
                    b.HasOne("Pictures.Domain.Entities.User", "User")
                        .WithMany("Pictures")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pictures.Domain.Entities.User", b =>
                {
                    b.Navigation("Pictures");
                });
#pragma warning restore 612, 618
        }
    }
}
